CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    author_name VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    password VARCHAR(255) NOT NULL,
    views INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);